// Generated by https://quicktype.io

export interface OrthographyResponse {
    userScore: number;
    errors:    string[];
    message:   string;
}


export interface OrthographyResponseData{
    userScore: number;
    errors: string[];
    message: string;
    ok: boolean;
}
